# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Use the Gibbs sampler to generate a chain by C++
#' @description Use the Gibbs sampler to generate a chain by C++
#' @param N the length of chain
#' @param a Initial parameters
#' @param b Initial parameters
#' @param n Initial parameters
#' @return a Gibbs sample chain
#' @examples
#' \dontrun{
#' N <- 1e4;a<-4;b<-4;n<-10 #Initial value
#' chainsC<-chainC_HW10(N,a,b,n)
#' }
#' @export 
chainC_HW10 <- function(N, a, b, n) {
    .Call(`_StatComp21089_chainC_HW10`, N, a, b, n)
}

